#python 3
from nltk import word_tokenize
import math
import pickle
import matplotlib.pyplot as plt


# read in the list of texts generated by readCorpus
with open('texts.pkl', 'rb') as f:
   texts = pickle.load(f)

# Coresponding Dates for weeks 0 - 9
dates = ["Dec 03 - Dec 09", "Dec 10 - Dec 16", "Dec 17 - Dec 23", 
        "Dec 24 - Dec 30", "Dec 31 - Jan 06", "Jan 07 - Jan 13", 
        "Jan 14 - Jan 20", "Jan 21 - Jan 27", "Jan 28 - Feb 03", 
        "Feb 10 - Feb 17"]

# Now in texts[0] is all the text up to 00250023 and texts[1] has 00250023 to 00970095 and so on
# need to tokenize each element in texts and then calculate word frequencies, will use nltk
searchword = "union"
freqs = []
occs = []
totals = []
for i in range (0, len(texts)):
    raw = texts[i].lower()
    words = word_tokenize(raw)
    occurances = words.count(searchword)
    total = len(words)
    frequency = float(occurances) / float(total)

    occs.append(occurances)
    totals.append(total)

    if (frequency > 0):
        freqs.append(math.log10(frequency))
    else:
        freqs.append(0)

plt.plot([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], freqs, 'ro')
plt.show()

